version: "3.8"

services:
  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  # https://github.com/deviantony/docker-elk/blob/main/elasticsearch/config/elasticsearch.yml
  metricbeat:
    image: my_metricbeat
    build: /var/www/es/current/metricbeat
    command: ["run", "-e", "--system.hostfs=/hostfs"]
    environment:
      - ELASTICSEARCH_PASSWORD=S0nic123
      - ELASTICSEARCH_USERNAME=mb_setup
      - ELASTICSEARCH_HOSTS=https://elasticsearch:9200
    volumes:
      - "/var/www/es/shared/ca/out:/certs"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro"
      - "/proc:/hostfs/proc:ro"
      - "/:/hostfs:ro"
    networks:
      - my-net

networks:
  my-net:
    external: true
